CC = g++
CFLAGS = -std=c++11 -I  -Wall

Default: p1 p2 p3 p4 p5 p7

p1: problem1.cpp
	$(CC) $(CFLAGS) -o assignment1 problem1.cpp

p2: problem2.cpp
	$(CC) $(CFLAGS) -o assignment2 problem2.cpp

p3: testWindGauge.cpp WindGauge.cpp WindGauge.h
	$(CC) $(CFLAGS) -o assignment3 testWindGauge.cpp WindGauge.cpp

p4: problem4.cpp
	$(CC) $(CFLAGS) -o assignment4 problem4.cpp

p5: problem5.cpp
	$(CC) $(CFLAGS) -o assignment5 problem5.cpp

p7: problem7.cpp
	$(CC) $(CFLAGS) -o assignment7 problem7.cpp
