CC = G++
CFLAGS = -std=c++11 -Wall
default: p1 p2 bonus

p1: DynProg1/main.cpp
	$(CC) $(CFLAGS) -I./DynProg1 -o problem1 DynProg1/main.cpp

p2: DynProg2/main.cpp
	$(CC) $(CFLAGS) -I./DynProg2 -o problem2 DynProg2/main.cpp
	
bonus: Scubadiver/main.cpp
	$(CC) $(CFLAGS) -I./Scubadiver -o bonus_problem Scubadiver/main.cpp