CC = g++
CFLAGS = -std=c++11 -o

Default: p6 p8

p6:
	$(CC) $(CFLAGS) problem6 -I. -I/A2.6/ A2.6/Access.cpp A2.6/testAccess.cpp

p8:
	$(CC) $(CFLAGS) problem8 -I. -I/A2.8/ A2.8/Access.cpp A2.8/testAccess.cpp