CC= g++
CFLAGS = -std=c++11 -I. -Wall -o

default: a b bonus

a: testStacks.cpp
	$(CC) $(CFLAGS) test_stacks testStacks.cpp
b: testLL_BST.cpp
	$(CC) $(CFLAGS)  test_LL_BST testLL_BST.cpp
bonus: test_bonus.cpp
	$(CC) $(CFLAGS) test_bonus test_bonus.cpp